Building Automation Framework: XDevice Class Reference
XDevice Class Reference
class XDevice as Testing-Object.
#include <XDevice.h>
Public Member Functions
virtual std::string decode (double dbl)
virtual double encode (std::string str)
double get_factor () const
std::string get_identifier () const
Getter for identifier.
std::string get_location () const
getter for location of device file.
double get_offset () const
std::string get_unit () const
Getter for member 'unit'.
double get_value ()
Read out XDevice.
XDevice & operator= (XDevice const &c)
Assignment-Operator.
virtual std::string receive ()
Function to read a string from a device.
virtual void send (std::string data)
Function to write a string to a device.
void set_factor (double d)
void set_identifier (std::string id)
Setter for identifier.
void set_location (std::string loc)
setter for location of device file.
void set_offset (double d)
void set_unit (std::string u)
Setter for member 'unit'.
void set_value (double v)
Set the value of XDevice.
XDevice (std::string id, std::string loc, std::string u, double o, double f)
Default-Constructor.
XDevice (std::string id, std::string loc, std::string u)
Constructor with lesser params.
XDevice (const XDevice &c)
Copy-Constructor.
virtual ~XDevice ()
Destructor.
Protected Attributes
std::string _identifier
String as identifier for this instance.
Private Attributes
std::string _unit
String representation of devices unit.
Detailed Description
class XDevice as Testing-Object.
Todo:
Instanciation via Factory?
This class is for testing purposes only. It encapsulates a Character-Device with an encoder for direct access of the devices numeric value.
Definition at line 26 of file XDevice.h.
Constructor & Destructor Documentation
XDevice::XDevice (std::string id, std::string loc, std::string u, double o, double f)
Default-Constructor.
Parameters
id
loc
u
o
f This constructor calls the default constructors in class 'CharacterDevice' (parameters: 'id' and 'loc') and class 'NumericEncoder' (parameters: 'o' and 'f'). After that the member variable 'unit' is set.
Definition at line 15 of file XDevice.cpp.
References _unit.
XDevice::XDevice (std::string id, std::string loc, std::string u)
Constructor with lesser params.
Parameters
id
loc
u This constructor calls the default constructors in class 'CharacterDevice' (parameters: 'id' and 'loc') and class 'NumericEncoder' (no parameters). After that the member variable 'unit' is set.
Definition at line 27 of file XDevice.cpp.
References _unit.
XDevice::XDevice (const XDevice & c)
Copy-Constructor.
Parameters
c The copy constructor instanciates 'this' object with the state of another instance of type 'XDevice.
Definition at line 37 of file XDevice.cpp.
References _unit, and get_unit().
XDevice::~XDevice () virtual
Destructor.
Destructor frees ressorces.
Definition at line 47 of file XDevice.cpp.
Member Function Documentation
std::string NumericEncoder::decode (double dbl) virtual inherited
Parameters
dbl
Returns
Deprecated:
Switched to std::stringstream for string-double conversion due to bad performance of boost::lexical_cast<T1>(T2 val).
Definition at line 98 of file NumericEncoder.cpp.
References NumericEncoder::_factor, and NumericEncoder::_offset.
Referenced by set_value().
double NumericEncoder::encode (std::string str) virtual inherited
Parameters
str
Returns
Deprecated:
Switched to std::stringstream for string-double conversion due to bad performance of boost::lexical_cast<T1>(T2 val).
Definition at line 77 of file NumericEncoder.cpp.
References NumericEncoder::_factor, and NumericEncoder::_offset.
Referenced by get_value().
double NumericEncoder::get_factor () const inherited
Returns
Definition at line 65 of file NumericEncoder.cpp.
References NumericEncoder::_factor.
Referenced by NumericEncoder::NumericEncoder(), NumericEncoder::operator=(), and operator=().
std::string AbstractDevice< std::string >::get_identifier () const inline inherited
Getter for identifier.
Returns
Current identifier.
Definition at line 46 of file AbstractDevice.h.
References AbstractDevice< T >::_identifier.
std::string CharacterDevice::get_location () const inherited
getter for location of device file.
Returns
String representing location of file.
Todo:
Implementaion for location getter with return type 'char*'.
Definition at line 37 of file CharacterDevice.cpp.
References CharacterDevice::_location.
Referenced by operator=().
double NumericEncoder::get_offset () const inherited
Returns
Definition at line 55 of file NumericEncoder.cpp.
References NumericEncoder::_offset.
Referenced by NumericEncoder::NumericEncoder(), NumericEncoder::operator=(), and operator=().
std::string XDevice::get_unit () const
Getter for member 'unit'.
Returns
State/value of member 'unit'
Definition at line 67 of file XDevice.cpp.
References _unit.
Referenced by operator=(), and XDevice().
double XDevice::get_value ()
Read out XDevice.
Returns
Current value read from XDevice.
This member reads out the raw data of the device and converts it into another format.
Switched to StringStream due to bad performance of boost::lexical_cast< T1 >(T2 arg)
Definition at line 79 of file XDevice.cpp.
References NumericEncoder::encode(), and CharacterDevice::receive().
XDevice & XDevice::operator= (XDevice const & c)
Assignment-Operator.
Parameters
c Assignment-Operator sets the state of 'this' instance to the state of another instance of type XDevice. It returns the address in memory of 'this' object.
Definition at line 53 of file XDevice.cpp.
References NumericEncoder::get_factor(), AbstractDevice< T >::get_identifier(), CharacterDevice::get_location(), NumericEncoder::get_offset(), get_unit(), NumericEncoder::set_factor(), AbstractDevice< std::string >::set_identifier(), CharacterDevice::set_location(), NumericEncoder::set_offset(), and set_unit().
std::string CharacterDevice::receive () virtual inherited
Function to read a string from a device.
Returns
String.
Implements AbstractDevice< std::string >.
Definition at line 63 of file CharacterDevice.cpp.
References CharacterDevice::_location.
Referenced by get_value().
void CharacterDevice::send (std::string data) virtual inherited
Function to write a string to a device.
Parameters
data String to write.
Implements AbstractDevice< std::string >.
Definition at line 48 of file CharacterDevice.cpp.
References CharacterDevice::_location.
Referenced by set_value().
void NumericEncoder::set_factor (double d) inherited
Parameters
d
Definition at line 70 of file NumericEncoder.cpp.
References NumericEncoder::_factor.
Referenced by NumericEncoder::operator=(), and operator=().
void AbstractDevice< std::string >::set_identifier (std::string id) inline inherited
Setter for identifier.
Parameters
String for new identifier.
Todo:
Setter for identifier with char*-type param.
Definition at line 40 of file AbstractDevice.h.
References AbstractDevice< T >::_identifier.
Referenced by operator=().
void CharacterDevice::set_location (std::string loc) inherited
setter for location of device file.
Parameters
loc String representing location of file.
Todo:
Implementaion for location setter with param of type 'char*'.
Definition at line 42 of file CharacterDevice.cpp.
References CharacterDevice::_location.
Referenced by operator=().
void NumericEncoder::set_offset (double d) inherited
Parameters
d
Definition at line 60 of file NumericEncoder.cpp.
References NumericEncoder::_offset.
Referenced by NumericEncoder::operator=(), and operator=().
void XDevice::set_unit (std::string u)
Setter for member 'unit'.
Parameters
u State/value for member 'unit'
Definition at line 72 of file XDevice.cpp.
References _unit.
Referenced by operator=().
void XDevice::set_value (double v)
Set the value of XDevice.
Parameters
v Value to set.
This function sends the converted value to the device.
Definition at line 98 of file XDevice.cpp.
References NumericEncoder::decode(), and CharacterDevice::send().
Field Documentation
std::string AbstractDevice< std::string >::_identifier protected inherited
String as identifier for this instance.
Definition at line 68 of file AbstractDevice.h.
std::string XDevice::_unit private
String representation of devices unit.
Definition at line 95 of file XDevice.h.
Referenced by get_unit(), set_unit(), and XDevice().
The documentation for this class was generated from the following files:
src/dev/XDevice.h
src/dev/XDevice.cpp