Building Automation Framework: NumericEncoder Class Reference
NumericEncoder Class Reference
#include <NumericEncoder.h>
Public Member Functions
virtual std::string decode (double dbl)
virtual double encode (std::string str)
double get_factor () const
double get_offset () const
NumericEncoder ()
NumericEncoder (double o, double f)
NumericEncoder (const NumericEncoder &enc)
NumericEncoder & operator= (const NumericEncoder &enc)
void set_factor (double d)
void set_offset (double d)
~NumericEncoder ()
Private Attributes
double _factor
double _offset
Detailed Description
Definition at line 17 of file NumericEncoder.h.
Constructor & Destructor Documentation
NumericEncoder::NumericEncoder ()
Definition at line 12 of file NumericEncoder.cpp.
References _factor, and _offset.
NumericEncoder::NumericEncoder (double o, double f)
Parameters
o
f
Definition at line 21 of file NumericEncoder.cpp.
References _factor, and _offset.
NumericEncoder::NumericEncoder (const NumericEncoder & enc)
Parameters
enc
Definition at line 30 of file NumericEncoder.cpp.
References _factor, _offset, get_factor(), and get_offset().
NumericEncoder::~NumericEncoder ()
Definition at line 39 of file NumericEncoder.cpp.
Member Function Documentation
std::string NumericEncoder::decode (double dbl) virtual
Parameters
dbl
Returns
Deprecated:
Switched to std::stringstream for string-double conversion due to bad performance of boost::lexical_cast<T1>(T2 val).
Definition at line 98 of file NumericEncoder.cpp.
References _factor, and _offset.
Referenced by XDevice::set_value().
double NumericEncoder::encode (std::string str) virtual
Parameters
str
Returns
Deprecated:
Switched to std::stringstream for string-double conversion due to bad performance of boost::lexical_cast<T1>(T2 val).
Definition at line 77 of file NumericEncoder.cpp.
References _factor, and _offset.
Referenced by XDevice::get_value().
double NumericEncoder::get_factor () const
Returns
Definition at line 65 of file NumericEncoder.cpp.
References _factor.
Referenced by NumericEncoder(), operator=(), and XDevice::operator=().
double NumericEncoder::get_offset () const
Returns
Definition at line 55 of file NumericEncoder.cpp.
References _offset.
Referenced by NumericEncoder(), operator=(), and XDevice::operator=().
NumericEncoder & NumericEncoder::operator= (const NumericEncoder & enc)
Parameters
enc
Definition at line 44 of file NumericEncoder.cpp.
References get_factor(), get_offset(), set_factor(), and set_offset().
void NumericEncoder::set_factor (double d)
Parameters
d
Definition at line 70 of file NumericEncoder.cpp.
References _factor.
Referenced by operator=(), and XDevice::operator=().
void NumericEncoder::set_offset (double d)
Parameters
d
Definition at line 60 of file NumericEncoder.cpp.
References _offset.
Referenced by operator=(), and XDevice::operator=().
Field Documentation
double NumericEncoder::_factor private
Definition at line 100 of file NumericEncoder.h.
Referenced by decode(), encode(), get_factor(), NumericEncoder(), and set_factor().
double NumericEncoder::_offset private
Definition at line 95 of file NumericEncoder.h.
Referenced by decode(), encode(), get_offset(), NumericEncoder(), and set_offset().
The documentation for this class was generated from the following files:
src/enc/NumericEncoder.h
src/enc/NumericEncoder.cpp