Building Automation Framework: CharacterDevice Class Reference
CharacterDevice Class Reference
Class CharacterDevice is a specialization of template class AbstractDevice. This class reads files of char devices on unix systems.
#include <CharacterDevice.h>
Public Member Functions
CharacterDevice (std::string id, std::string loc)
Constructor to instanciate character devices.
std::string get_identifier () const
Getter for identifier.
std::string get_location () const
getter for location of device file.
virtual std::string receive ()
Function to read a string from a device.
virtual void send (std::string data)
Function to write a string to a device.
void set_identifier (std::string id)
Setter for identifier.
void set_location (std::string loc)
setter for location of device file.
virtual ~CharacterDevice ()
(Virtual) Destructor. This destructor is virtual to be called on inherited destructors.
Protected Member Functions
CharacterDevice (std::string id)
Second constructor.
Protected Attributes
std::string _identifier
String as identifier for this instance.
Private Attributes
std::string _location
Location of file for this instance.
Detailed Description
Class CharacterDevice is a specialization of template class AbstractDevice. This class reads files of char devices on unix systems.
Definition at line 16 of file CharacterDevice.h.
Constructor & Destructor Documentation
CharacterDevice::CharacterDevice (std::string id, std::string loc)
Constructor to instanciate character devices.
Parameters:
id A string to identify the device. This id is given to an instance of template class 'AbstractDevice'.
loc Location of character device on the system.
Definition at line 13 of file CharacterDevice.cpp.
References _location.
CharacterDevice::~CharacterDevice () [virtual]
(Virtual) Destructor. This destructor is virtual to be called on inherited destructors.
Definition at line 27 of file CharacterDevice.cpp.
CharacterDevice::CharacterDevice (std::string id) [protected]
Second constructor.
Parameters:
id Identifier for device. This constructor is only allowed for directly inheriting structures.
Definition at line 22 of file CharacterDevice.cpp.
Member Function Documentation
std::string AbstractDevice< std::string >::get_identifier () const [inline, inherited]
Getter for identifier.
Returns:
Current identifier.
Definition at line 46 of file AbstractDevice.h.
References AbstractDevice< T >::_identifier.
std::string CharacterDevice::get_location () const
getter for location of device file.
Returns:
String representing location of file.
Todo:
Implementaion for location getter with return type 'char*'.
Definition at line 37 of file CharacterDevice.cpp.
References _location.
Referenced by XDevice::operator=().
std::string CharacterDevice::receive () [virtual]
Function to read a string from a device.
Returns:
String.
Implements AbstractDevice< std::string >.
Definition at line 63 of file CharacterDevice.cpp.
References _location.
Referenced by XDevice::get_value(), and main().
void CharacterDevice::send (std::string data) [virtual]
Function to write a string to a device.
Parameters:
data String to write.
Implements AbstractDevice< std::string >.
Definition at line 48 of file CharacterDevice.cpp.
References _location.
Referenced by main(), and XDevice::set_value().
void AbstractDevice< std::string >::set_identifier (std::string id) [inline, inherited]
Setter for identifier.
Parameters:
String for new identifier.
Todo:
Setter for identifier with char*-type param.
Definition at line 40 of file AbstractDevice.h.
References AbstractDevice< T >::_identifier.
Referenced by XDevice::operator=().
void CharacterDevice::set_location (std::string loc)
setter for location of device file.
Parameters:
loc String representing location of file.
Todo:
Implementaion for location setter with param of type 'char*'.
Definition at line 42 of file CharacterDevice.cpp.
References _location.
Referenced by XDevice::operator=().
Field Documentation
std::string AbstractDevice< std::string >::_identifier [protected, inherited]
String as identifier for this instance.
Definition at line 68 of file AbstractDevice.h.
std::string CharacterDevice::_location [private]
Location of file for this instance.
Definition at line 77 of file CharacterDevice.h.
Referenced by CharacterDevice(), get_location(), receive(), send(), and set_location().
The documentation for this class was generated from the following files:
src/dev/CharacterDevice.h
src/dev/CharacterDevice.cpp