Building Automation Framework: src/shared.cpp File Reference
shared.cpp File Reference
#include "shared.h"
Functions
std::vector< std::string > list_devices (std::string p, unsigned char t, bool rec)
Getting filenames associated with a special filetype.
std::map< int, std::vector
< std::string > > map_devices (std::string p, bool rec)
Map all devices of a directory, sorted by their filetype.
Detailed Description
Author:
t.j.
Version:
2013-09
Definition in file shared.cpp.
Function Documentation
std::vector< std::string > list_devices (std::string dir, unsigned char ftype, bool rec = false)
Getting filenames associated with a special filetype.
Parameters:
dir Directory to scan.
ftype What files to list.
rec Scan recursively. Default is false.
Returns:
Vector containing Strings containing filenames.
This function scans a given directory for a special filetype. The filetypes are defined within the 'dirent.h'
Definition at line 12 of file shared.cpp.
References list_devices().
Referenced by list_devices(), main(), and map_devices().
std::map< int, std::vector< std::string > > map_devices (std::string dir, bool rec = true)
Map all devices of a directory, sorted by their filetype.
Parameters:
dir Path to the directory to scan.
rec Wether the path should be scanned recursively.
Returns:
A Map with int values as key and string vectors containing the filenames of each file associated to a filetype.
Definition at line 53 of file shared.cpp.
References FT_BLK, FT_CHR, FT_DIR, FT_FIFO, FT_LNK, FT_REG, FT_SOCK, FT_UKN, and list_devices().