Building Automation Framework: src/shared.h File Reference
shared.h File Reference
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <map>
#include <stdlib.h>
#include <dirent.h>
#include <sys/types.h>
#include <string.h>
Enumerations
enum FTYPE {
FT_UKN = 0, FT_DIR = 1, FT_REG = 2, FT_BLK = 3,
FT_LNK = 4, FT_CHR = 5, FT_SOCK = 6, FT_FIFO = 7
}
Coding Filtetypes in extra enum. This extra enum, encoding DT_Filetypes is necessary due to type problems in std::map with unsigned char as key type.
Functions
std::vector< std::string > list_devices (std::string dir, unsigned char ftype, bool rec=false)
Getting filenames associated with a special filetype.
std::map< int, std::vector
< std::string > > map_devices (std::string dir, bool rec=true)
Map all devices of a directory, sorted by their filetype.
Detailed Description
Author
t.j.
Version
2013-09
Definition in file shared.h.
Enumeration Type Documentation
enum FTYPE
Coding Filtetypes in extra enum. This extra enum, encoding DT_Filetypes is necessary due to type problems in std::map with unsigned char as key type.
Enumerator:
FT_UKN
FT_DIR
FT_REG
FT_BLK
FT_LNK
FT_CHR
FT_SOCK
FT_FIFO
Definition at line 28 of file shared.h.
Function Documentation
std::vector<std::string> list_devices (std::string dir, unsigned char ftype, bool rec = false)
Getting filenames associated with a special filetype.
Parameters
dir Directory to scan.
ftype What files to list.
rec Scan recursively. Default is false.
Returns
Vector containing Strings containing filenames.
This function scans a given directory for a special filetype. The filetypes are defined within the 'dirent.h'
Definition at line 12 of file shared.cpp.
References list_devices().
Referenced by list_devices(), main(), and map_devices().
std::map< int, std::vector< std::string > > map_devices (std::string dir, bool rec = true)
Map all devices of a directory, sorted by their filetype.
Parameters
dir Path to the directory to scan.
rec Wether the path should be scanned recursively.
Returns
A Map with int values as key and string vectors containing the filenames of each file associated to a filetype.
Definition at line 53 of file shared.cpp.
References FT_BLK, FT_CHR, FT_DIR, FT_FIFO, FT_LNK, FT_REG, FT_SOCK, FT_UKN, and list_devices().